// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqzejkvwwxyzmzjnhcmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxemVqa3Z3d3h5em16am5oY21tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNTMwMjMsImV4cCI6MjA4NjkyOTAyM30.0CSRrOCZLbsBXmCYndUtYalE9TRRK1FccNltFv7HyrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});